"""new table

Revision ID: 51b874ba1d46
Revises: 8b2f0d1e6a4c
Create Date: 2026-10-03 18:28:48.547142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b874ba1d46'
down_revision: Union[str, Sequence[str], None] = '8b2f0d1e6a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_reads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('demande_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demande_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demande_events_actor_id'), 'demande_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_demande_events_created_at'), 'demande_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_demande_events_demande_id'), 'demande_events', ['demande_id'], unique=False)
    op.create_index(op.f('ix_demande_events_type'), 'demande_events', ['type'], unique=False)
    op.create_index(op.f('ix_citizen_requests_status'), 'citizen_requests', ['status'], unique=False)
    op.drop_constraint(op.f('citizen_requests_citizen_id_fkey'), 'citizen_requests', type_='foreignkey')
    op.create_foreign_key(None, 'citizen_requests', 'users', ['citizen_id'], ['id'])
    op.drop_constraint(op.f('contact_messages_receipt_number_key'), 'contact_messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('contact_messages_receipt_number_key'), 'contact_messages', ['receipt_number'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'citizen_requests', type_='foreignkey')
    op.create_foreign_key(op.f('citizen_requests_citizen_id_fkey'), 'citizen_requests', 'users', ['citizen_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_citizen_requests_status'), table_name='citizen_requests')
    op.drop_index(op.f('ix_demande_events_type'), table_name='demande_events')
    op.drop_index(op.f('ix_demande_events_demande_id'), table_name='demande_events')
    op.drop_index(op.f('ix_demande_events_created_at'), table_name='demande_events')
    op.drop_index(op.f('ix_demande_events_actor_id'), table_name='demande_events')
    op.drop_table('demande_events')
    op.drop_table('notification_reads')
    # ### end Alembic commands ###
