"""create citizen requests

Revision ID: 462099655b53
Revises: c5476fb4d364
Create Date: 2026-10-01 00:03:23.720598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462099655b53'
down_revision: Union[str, Sequence[str], None] = 'c5476fb4d364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_requests_assigned_agent_id'), 'citizen_requests', ['assigned_agent_id'], unique=False)
    op.create_index('ix_citizen_requests_category', 'citizen_requests', ['category'], unique=False)
    op.create_index(op.f('ix_citizen_requests_citizen_id'), 'citizen_requests', ['citizen_id'], unique=False)
    op.create_index('ix_citizen_requests_status_created_at', 'citizen_requests', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citizen_requests_status_created_at', table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_citizen_id'), table_name='citizen_requests')
    op.drop_index('ix_citizen_requests_category', table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_assigned_agent_id'), table_name='citizen_requests')
    op.drop_table('citizen_requests')
    # ### end Alembic commands ###
