"""new version table

Revision ID: bb3a846f7e79
Revises: 91c8d3e6f45a
Create Date: 2026-10-04 06:51:26.830645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3a846f7e79'
down_revision: Union[str, Sequence[str], None] = '91c8d3e6f45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assistant_messages_user_id'), 'assistant_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_messages_user_id'), table_name='assistant_messages')
    # ### end Alembic commands ###
