"""add institut service management

Revision ID: 6a543df8a282
Revises: 7b3f9c0d1e48
Create Date: 2026-10-04 04:21:20.675000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a543df8a282'
down_revision: Union[str, Sequence[str], None] = '7b3f9c0d1e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipal_service_agents',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['municipal_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'agent_id')
    )
    op.add_column('municipal_services', sa.Column('institut_id', sa.String(length=36), nullable=True))
    op.add_column('municipal_services', sa.Column('responsible_agent_id', sa.String(length=36), nullable=True))
    op.add_column('municipal_services', sa.Column('request_category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_municipal_services_institut_id'), 'municipal_services', ['institut_id'], unique=False)
    op.create_index(op.f('ix_municipal_services_request_category'), 'municipal_services', ['request_category'], unique=False)
    op.create_index(op.f('ix_municipal_services_responsible_agent_id'), 'municipal_services', ['responsible_agent_id'], unique=False)
    op.create_foreign_key('fk_municipal_services_institut', 'municipal_services', 'instituts', ['institut_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_municipal_services_responsible_agent', 'municipal_services', 'agents', ['responsible_agent_id'], ['id'], ondelete='SET NULL')
    # Rattache le catalogue de référence déjà livré aux instituts créés précédemment.
    op.execute(sa.text("""
        UPDATE municipal_services
        SET institut_id = '10000000-0000-0000-0000-000000000011'
        WHERE id IN (
            '10000000-0000-0000-0000-000000000004', '10000000-0000-0000-0000-000000000005',
            '10000000-0000-0000-0000-000000000006', '10000000-0000-0000-0000-000000000007',
            '10000000-0000-0000-0000-000000000008', '10000000-0000-0000-0000-000000000009',
            '10000000-0000-0000-0000-000000000020', '10000000-0000-0000-0000-000000000021',
            '10000000-0000-0000-0000-000000000022', '10000000-0000-0000-0000-000000000023',
            '10000000-0000-0000-0000-000000000024'
        )
    """))
    op.execute(sa.text("""
        UPDATE municipal_services
        SET institut_id = '10000000-0000-0000-0000-000000000017', request_category = 'Sécurité'
        WHERE id = '10000000-0000-0000-0000-000000000010'
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_municipal_services_responsible_agent', 'municipal_services', type_='foreignkey')
    op.drop_constraint('fk_municipal_services_institut', 'municipal_services', type_='foreignkey')
    op.drop_index(op.f('ix_municipal_services_responsible_agent_id'), table_name='municipal_services')
    op.drop_index(op.f('ix_municipal_services_request_category'), table_name='municipal_services')
    op.drop_index(op.f('ix_municipal_services_institut_id'), table_name='municipal_services')
    op.drop_column('municipal_services', 'request_category')
    op.drop_column('municipal_services', 'responsible_agent_id')
    op.drop_column('municipal_services', 'institut_id')
    op.drop_table('municipal_service_agents')
    # ### end Alembic commands ###
