"""publication reactions comments

Revision ID: d7ea06539991
Revises: 32c9ea93f393
Create Date: 2026-10-04 00:17:53.819924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ea06539991'
down_revision: Union[str, Sequence[str], None] = '32c9ea93f393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipal_publication_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['municipal_publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipal_publication_comments_created_at'), 'municipal_publication_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_municipal_publication_comments_publication_id'), 'municipal_publication_comments', ['publication_id'], unique=False)
    op.create_index(op.f('ix_municipal_publication_comments_user_id'), 'municipal_publication_comments', ['user_id'], unique=False)
    op.create_table('municipal_publication_likes',
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['municipal_publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipal_publication_likes')
    op.drop_index(op.f('ix_municipal_publication_comments_user_id'), table_name='municipal_publication_comments')
    op.drop_index(op.f('ix_municipal_publication_comments_publication_id'), table_name='municipal_publication_comments')
    op.drop_index(op.f('ix_municipal_publication_comments_created_at'), table_name='municipal_publication_comments')
    op.drop_table('municipal_publication_comments')
    # ### end Alembic commands ###
