"""publication media metrics

Revision ID: 32c9ea93f393
Revises: f2c8a5e1d4b6
Create Date: 2026-10-03 23:58:52.732105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32c9ea93f393"
down_revision: str | Sequence[str] | None = "f2c8a5e1d4b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "municipal_publications", sa.Column("image_url", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "municipal_publications",
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "municipal_publications",
        sa.Column("like_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("municipal_publications", "like_count")
    op.drop_column("municipal_publications", "view_count")
    op.drop_column("municipal_publications", "image_url")
    # ### end Alembic commands ###
