"""add email verification and Google identity

Revision ID: af323a8bae9b
Revises: c3f9a7d2e815
Create Date: 2026-10-03 21:12:09.656057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "af323a8bae9b"
down_revision: Union[str, Sequence[str], None] = "c3f9a7d2e815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("verification_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_verification_codes_user_id"), ["user_id"], unique=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email_verified", sa.Boolean(), server_default=sa.true(), nullable=False)
        )
        batch_op.add_column(sa.Column("google_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("avatar_url", sa.String(length=2048), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_google_id"), ["google_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_google_id"))
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("google_id")
        batch_op.drop_column("email_verified")

    with op.batch_alter_table("verification_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_codes_user_id"))

    op.drop_table("verification_codes")
    # ### end Alembic commands ###
